package com.idealighter.game.core.dao.generate.domain;

import java.io.Serializable;
import java.util.Date;

public class AppleInAppPayReceiptDataDomain implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apple_in_app_pay_receipt_data.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apple_in_app_pay_receipt_data.md5_check
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String md5Check;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apple_in_app_pay_receipt_data.create_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apple_in_app_pay_receipt_data.receipt_data
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String receiptData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table apple_in_app_pay_receipt_data
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apple_in_app_pay_receipt_data.id
     *
     * @return the value of apple_in_app_pay_receipt_data.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apple_in_app_pay_receipt_data.id
     *
     * @param id the value for apple_in_app_pay_receipt_data.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apple_in_app_pay_receipt_data.md5_check
     *
     * @return the value of apple_in_app_pay_receipt_data.md5_check
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getMd5Check() {
        return md5Check;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apple_in_app_pay_receipt_data.md5_check
     *
     * @param md5Check the value for apple_in_app_pay_receipt_data.md5_check
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setMd5Check(String md5Check) {
        this.md5Check = md5Check;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apple_in_app_pay_receipt_data.create_time
     *
     * @return the value of apple_in_app_pay_receipt_data.create_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apple_in_app_pay_receipt_data.create_time
     *
     * @param createTime the value for apple_in_app_pay_receipt_data.create_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apple_in_app_pay_receipt_data.receipt_data
     *
     * @return the value of apple_in_app_pay_receipt_data.receipt_data
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getReceiptData() {
        return receiptData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apple_in_app_pay_receipt_data.receipt_data
     *
     * @param receiptData the value for apple_in_app_pay_receipt_data.receipt_data
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setReceiptData(String receiptData) {
        this.receiptData = receiptData;
    }
}