package com.idealighter.game.core.dao.generate.domain;

import java.io.Serializable;
import java.util.Date;

public class BlackListDomain implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_list.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_list.limit_type
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String limitType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_list.limit_action
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String limitAction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_list.limit_value
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String limitValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_list.end_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table black_list
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_list.id
     *
     * @return the value of black_list.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_list.id
     *
     * @param id the value for black_list.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_list.limit_type
     *
     * @return the value of black_list.limit_type
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getLimitType() {
        return limitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_list.limit_type
     *
     * @param limitType the value for black_list.limit_type
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setLimitType(String limitType) {
        this.limitType = limitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_list.limit_action
     *
     * @return the value of black_list.limit_action
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getLimitAction() {
        return limitAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_list.limit_action
     *
     * @param limitAction the value for black_list.limit_action
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setLimitAction(String limitAction) {
        this.limitAction = limitAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_list.limit_value
     *
     * @return the value of black_list.limit_value
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getLimitValue() {
        return limitValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_list.limit_value
     *
     * @param limitValue the value for black_list.limit_value
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setLimitValue(String limitValue) {
        this.limitValue = limitValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_list.end_time
     *
     * @return the value of black_list.end_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_list.end_time
     *
     * @param endTime the value for black_list.end_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}