package com.idealighter.game.core.dao.generate.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BlackListDomainExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table black_list
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table black_list
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table black_list
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public BlackListDomainExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table black_list
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLimitTypeIsNull() {
            addCriterion("limit_type is null");
            return (Criteria) this;
        }

        public Criteria andLimitTypeIsNotNull() {
            addCriterion("limit_type is not null");
            return (Criteria) this;
        }

        public Criteria andLimitTypeEqualTo(String value) {
            addCriterion("limit_type =", value, "limitType");
            return (Criteria) this;
        }

        public Criteria andLimitTypeNotEqualTo(String value) {
            addCriterion("limit_type <>", value, "limitType");
            return (Criteria) this;
        }

        public Criteria andLimitTypeGreaterThan(String value) {
            addCriterion("limit_type >", value, "limitType");
            return (Criteria) this;
        }

        public Criteria andLimitTypeGreaterThanOrEqualTo(String value) {
            addCriterion("limit_type >=", value, "limitType");
            return (Criteria) this;
        }

        public Criteria andLimitTypeLessThan(String value) {
            addCriterion("limit_type <", value, "limitType");
            return (Criteria) this;
        }

        public Criteria andLimitTypeLessThanOrEqualTo(String value) {
            addCriterion("limit_type <=", value, "limitType");
            return (Criteria) this;
        }

        public Criteria andLimitTypeLike(String value) {
            addCriterion("limit_type like", value, "limitType");
            return (Criteria) this;
        }

        public Criteria andLimitTypeNotLike(String value) {
            addCriterion("limit_type not like", value, "limitType");
            return (Criteria) this;
        }

        public Criteria andLimitTypeIn(List<String> values) {
            addCriterion("limit_type in", values, "limitType");
            return (Criteria) this;
        }

        public Criteria andLimitTypeNotIn(List<String> values) {
            addCriterion("limit_type not in", values, "limitType");
            return (Criteria) this;
        }

        public Criteria andLimitTypeBetween(String value1, String value2) {
            addCriterion("limit_type between", value1, value2, "limitType");
            return (Criteria) this;
        }

        public Criteria andLimitTypeNotBetween(String value1, String value2) {
            addCriterion("limit_type not between", value1, value2, "limitType");
            return (Criteria) this;
        }

        public Criteria andLimitActionIsNull() {
            addCriterion("limit_action is null");
            return (Criteria) this;
        }

        public Criteria andLimitActionIsNotNull() {
            addCriterion("limit_action is not null");
            return (Criteria) this;
        }

        public Criteria andLimitActionEqualTo(String value) {
            addCriterion("limit_action =", value, "limitAction");
            return (Criteria) this;
        }

        public Criteria andLimitActionNotEqualTo(String value) {
            addCriterion("limit_action <>", value, "limitAction");
            return (Criteria) this;
        }

        public Criteria andLimitActionGreaterThan(String value) {
            addCriterion("limit_action >", value, "limitAction");
            return (Criteria) this;
        }

        public Criteria andLimitActionGreaterThanOrEqualTo(String value) {
            addCriterion("limit_action >=", value, "limitAction");
            return (Criteria) this;
        }

        public Criteria andLimitActionLessThan(String value) {
            addCriterion("limit_action <", value, "limitAction");
            return (Criteria) this;
        }

        public Criteria andLimitActionLessThanOrEqualTo(String value) {
            addCriterion("limit_action <=", value, "limitAction");
            return (Criteria) this;
        }

        public Criteria andLimitActionLike(String value) {
            addCriterion("limit_action like", value, "limitAction");
            return (Criteria) this;
        }

        public Criteria andLimitActionNotLike(String value) {
            addCriterion("limit_action not like", value, "limitAction");
            return (Criteria) this;
        }

        public Criteria andLimitActionIn(List<String> values) {
            addCriterion("limit_action in", values, "limitAction");
            return (Criteria) this;
        }

        public Criteria andLimitActionNotIn(List<String> values) {
            addCriterion("limit_action not in", values, "limitAction");
            return (Criteria) this;
        }

        public Criteria andLimitActionBetween(String value1, String value2) {
            addCriterion("limit_action between", value1, value2, "limitAction");
            return (Criteria) this;
        }

        public Criteria andLimitActionNotBetween(String value1, String value2) {
            addCriterion("limit_action not between", value1, value2, "limitAction");
            return (Criteria) this;
        }

        public Criteria andLimitValueIsNull() {
            addCriterion("limit_value is null");
            return (Criteria) this;
        }

        public Criteria andLimitValueIsNotNull() {
            addCriterion("limit_value is not null");
            return (Criteria) this;
        }

        public Criteria andLimitValueEqualTo(String value) {
            addCriterion("limit_value =", value, "limitValue");
            return (Criteria) this;
        }

        public Criteria andLimitValueNotEqualTo(String value) {
            addCriterion("limit_value <>", value, "limitValue");
            return (Criteria) this;
        }

        public Criteria andLimitValueGreaterThan(String value) {
            addCriterion("limit_value >", value, "limitValue");
            return (Criteria) this;
        }

        public Criteria andLimitValueGreaterThanOrEqualTo(String value) {
            addCriterion("limit_value >=", value, "limitValue");
            return (Criteria) this;
        }

        public Criteria andLimitValueLessThan(String value) {
            addCriterion("limit_value <", value, "limitValue");
            return (Criteria) this;
        }

        public Criteria andLimitValueLessThanOrEqualTo(String value) {
            addCriterion("limit_value <=", value, "limitValue");
            return (Criteria) this;
        }

        public Criteria andLimitValueLike(String value) {
            addCriterion("limit_value like", value, "limitValue");
            return (Criteria) this;
        }

        public Criteria andLimitValueNotLike(String value) {
            addCriterion("limit_value not like", value, "limitValue");
            return (Criteria) this;
        }

        public Criteria andLimitValueIn(List<String> values) {
            addCriterion("limit_value in", values, "limitValue");
            return (Criteria) this;
        }

        public Criteria andLimitValueNotIn(List<String> values) {
            addCriterion("limit_value not in", values, "limitValue");
            return (Criteria) this;
        }

        public Criteria andLimitValueBetween(String value1, String value2) {
            addCriterion("limit_value between", value1, value2, "limitValue");
            return (Criteria) this;
        }

        public Criteria andLimitValueNotBetween(String value1, String value2) {
            addCriterion("limit_value not between", value1, value2, "limitValue");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table black_list
     *
     * @mbg.generated do_not_delete_during_merge Tue Aug 14 14:13:21 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table black_list
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}