package com.idealighter.game.core.dao.generate.domain;

import java.io.Serializable;
import java.util.Date;

public class MailDomain implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.player_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Long playerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.player_super_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Long playerSuperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.player_name
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String playerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.from_player_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Long fromPlayerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.from_player_super_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Long fromPlayerSuperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.from_player_name
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String fromPlayerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.gold
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Long gold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.title
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.is_read
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Boolean isRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.is_rec_gold
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Boolean isRecGold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.create_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail.content
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mail
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.id
     *
     * @return the value of mail.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.id
     *
     * @param id the value for mail.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.player_id
     *
     * @return the value of mail.player_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Long getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.player_id
     *
     * @param playerId the value for mail.player_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setPlayerId(Long playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.player_super_id
     *
     * @return the value of mail.player_super_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Long getPlayerSuperId() {
        return playerSuperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.player_super_id
     *
     * @param playerSuperId the value for mail.player_super_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setPlayerSuperId(Long playerSuperId) {
        this.playerSuperId = playerSuperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.player_name
     *
     * @return the value of mail.player_name
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getPlayerName() {
        return playerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.player_name
     *
     * @param playerName the value for mail.player_name
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setPlayerName(String playerName) {
        this.playerName = playerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.from_player_id
     *
     * @return the value of mail.from_player_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Long getFromPlayerId() {
        return fromPlayerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.from_player_id
     *
     * @param fromPlayerId the value for mail.from_player_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setFromPlayerId(Long fromPlayerId) {
        this.fromPlayerId = fromPlayerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.from_player_super_id
     *
     * @return the value of mail.from_player_super_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Long getFromPlayerSuperId() {
        return fromPlayerSuperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.from_player_super_id
     *
     * @param fromPlayerSuperId the value for mail.from_player_super_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setFromPlayerSuperId(Long fromPlayerSuperId) {
        this.fromPlayerSuperId = fromPlayerSuperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.from_player_name
     *
     * @return the value of mail.from_player_name
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getFromPlayerName() {
        return fromPlayerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.from_player_name
     *
     * @param fromPlayerName the value for mail.from_player_name
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setFromPlayerName(String fromPlayerName) {
        this.fromPlayerName = fromPlayerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.gold
     *
     * @return the value of mail.gold
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Long getGold() {
        return gold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.gold
     *
     * @param gold the value for mail.gold
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setGold(Long gold) {
        this.gold = gold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.title
     *
     * @return the value of mail.title
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.title
     *
     * @param title the value for mail.title
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.is_read
     *
     * @return the value of mail.is_read
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Boolean getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.is_read
     *
     * @param isRead the value for mail.is_read
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.is_rec_gold
     *
     * @return the value of mail.is_rec_gold
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Boolean getIsRecGold() {
        return isRecGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.is_rec_gold
     *
     * @param isRecGold the value for mail.is_rec_gold
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setIsRecGold(Boolean isRecGold) {
        this.isRecGold = isRecGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.create_time
     *
     * @return the value of mail.create_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.create_time
     *
     * @param createTime the value for mail.create_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail.content
     *
     * @return the value of mail.content
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail.content
     *
     * @param content the value for mail.content
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }
}