package com.idealighter.game.core.dao.generate.domain;

import java.io.Serializable;

public class PlayerGameInfoDomain implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_game_info.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_game_info.player_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Long playerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table player_game_info
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_game_info.id
     *
     * @return the value of player_game_info.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_game_info.id
     *
     * @param id the value for player_game_info.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_game_info.player_id
     *
     * @return the value of player_game_info.player_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Long getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_game_info.player_id
     *
     * @param playerId the value for player_game_info.player_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setPlayerId(Long playerId) {
        this.playerId = playerId;
    }
}