package com.idealighter.game.core.dao.generate.domain;

import java.io.Serializable;

public class PlayerVipDomain implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_vip.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_vip.player_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Long playerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_vip.play_item_effect
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Boolean playItemEffect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_vip.table_limit_gold
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Long tableLimitGold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_vip.table_limit_gold_abled
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Boolean tableLimitGoldAbled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_vip.table_limit_ip
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Boolean tableLimitIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_vip.table_pwd
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String tablePwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_vip.table_pwd_abled
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Boolean tablePwdAbled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_vip.room_setting_abled
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Boolean roomSettingAbled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table player_vip
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_vip.id
     *
     * @return the value of player_vip.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_vip.id
     *
     * @param id the value for player_vip.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_vip.player_id
     *
     * @return the value of player_vip.player_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Long getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_vip.player_id
     *
     * @param playerId the value for player_vip.player_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setPlayerId(Long playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_vip.play_item_effect
     *
     * @return the value of player_vip.play_item_effect
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Boolean getPlayItemEffect() {
        return playItemEffect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_vip.play_item_effect
     *
     * @param playItemEffect the value for player_vip.play_item_effect
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setPlayItemEffect(Boolean playItemEffect) {
        this.playItemEffect = playItemEffect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_vip.table_limit_gold
     *
     * @return the value of player_vip.table_limit_gold
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Long getTableLimitGold() {
        return tableLimitGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_vip.table_limit_gold
     *
     * @param tableLimitGold the value for player_vip.table_limit_gold
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setTableLimitGold(Long tableLimitGold) {
        this.tableLimitGold = tableLimitGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_vip.table_limit_gold_abled
     *
     * @return the value of player_vip.table_limit_gold_abled
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Boolean getTableLimitGoldAbled() {
        return tableLimitGoldAbled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_vip.table_limit_gold_abled
     *
     * @param tableLimitGoldAbled the value for player_vip.table_limit_gold_abled
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setTableLimitGoldAbled(Boolean tableLimitGoldAbled) {
        this.tableLimitGoldAbled = tableLimitGoldAbled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_vip.table_limit_ip
     *
     * @return the value of player_vip.table_limit_ip
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Boolean getTableLimitIp() {
        return tableLimitIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_vip.table_limit_ip
     *
     * @param tableLimitIp the value for player_vip.table_limit_ip
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setTableLimitIp(Boolean tableLimitIp) {
        this.tableLimitIp = tableLimitIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_vip.table_pwd
     *
     * @return the value of player_vip.table_pwd
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getTablePwd() {
        return tablePwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_vip.table_pwd
     *
     * @param tablePwd the value for player_vip.table_pwd
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setTablePwd(String tablePwd) {
        this.tablePwd = tablePwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_vip.table_pwd_abled
     *
     * @return the value of player_vip.table_pwd_abled
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Boolean getTablePwdAbled() {
        return tablePwdAbled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_vip.table_pwd_abled
     *
     * @param tablePwdAbled the value for player_vip.table_pwd_abled
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setTablePwdAbled(Boolean tablePwdAbled) {
        this.tablePwdAbled = tablePwdAbled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_vip.room_setting_abled
     *
     * @return the value of player_vip.room_setting_abled
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Boolean getRoomSettingAbled() {
        return roomSettingAbled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_vip.room_setting_abled
     *
     * @param roomSettingAbled the value for player_vip.room_setting_abled
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setRoomSettingAbled(Boolean roomSettingAbled) {
        this.roomSettingAbled = roomSettingAbled;
    }
}