package com.idealighter.game.core.dao.generate.domain;

import java.io.Serializable;
import java.util.Date;

public class PlayerStatusRecordDomain implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_status_record.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_status_record.player_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Long playerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_status_record.register_ip
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String registerIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_status_record.register_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Date registerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_status_record.login_ip
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String loginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_status_record.login_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Date loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_status_record.login_count
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Integer loginCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_status_record.logout_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Date logoutTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_status_record.gametime
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Long gametime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_status_record.onlinetime
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Long onlinetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_status_record.update_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table player_status_record
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_status_record.id
     *
     * @return the value of player_status_record.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_status_record.id
     *
     * @param id the value for player_status_record.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_status_record.player_id
     *
     * @return the value of player_status_record.player_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Long getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_status_record.player_id
     *
     * @param playerId the value for player_status_record.player_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setPlayerId(Long playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_status_record.register_ip
     *
     * @return the value of player_status_record.register_ip
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getRegisterIp() {
        return registerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_status_record.register_ip
     *
     * @param registerIp the value for player_status_record.register_ip
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setRegisterIp(String registerIp) {
        this.registerIp = registerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_status_record.register_time
     *
     * @return the value of player_status_record.register_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_status_record.register_time
     *
     * @param registerTime the value for player_status_record.register_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_status_record.login_ip
     *
     * @return the value of player_status_record.login_ip
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_status_record.login_ip
     *
     * @param loginIp the value for player_status_record.login_ip
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_status_record.login_time
     *
     * @return the value of player_status_record.login_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_status_record.login_time
     *
     * @param loginTime the value for player_status_record.login_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_status_record.login_count
     *
     * @return the value of player_status_record.login_count
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Integer getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_status_record.login_count
     *
     * @param loginCount the value for player_status_record.login_count
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setLoginCount(Integer loginCount) {
        this.loginCount = loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_status_record.logout_time
     *
     * @return the value of player_status_record.logout_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Date getLogoutTime() {
        return logoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_status_record.logout_time
     *
     * @param logoutTime the value for player_status_record.logout_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setLogoutTime(Date logoutTime) {
        this.logoutTime = logoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_status_record.gametime
     *
     * @return the value of player_status_record.gametime
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Long getGametime() {
        return gametime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_status_record.gametime
     *
     * @param gametime the value for player_status_record.gametime
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setGametime(Long gametime) {
        this.gametime = gametime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_status_record.onlinetime
     *
     * @return the value of player_status_record.onlinetime
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Long getOnlinetime() {
        return onlinetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_status_record.onlinetime
     *
     * @param onlinetime the value for player_status_record.onlinetime
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setOnlinetime(Long onlinetime) {
        this.onlinetime = onlinetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_status_record.update_time
     *
     * @return the value of player_status_record.update_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_status_record.update_time
     *
     * @param updateTime the value for player_status_record.update_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}