package com.idealighter.game.core.dao.generate.domain;

import java.io.Serializable;

public class PlayerSafeInfoDomain implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_safe_info.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_safe_info.player_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Long playerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_safe_info.validate_phone
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Boolean validatePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_safe_info.validate_email
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Boolean validateEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_safe_info.first_pwd_protect_q
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String firstPwdProtectQ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_safe_info.first_pwd_protect_a
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String firstPwdProtectA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_safe_info.second_pwd_protect_q
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String secondPwdProtectQ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_safe_info.second_pwd_protect_a
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String secondPwdProtectA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_safe_info.login_phone_verify
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Boolean loginPhoneVerify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table player_safe_info
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_safe_info.id
     *
     * @return the value of player_safe_info.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_safe_info.id
     *
     * @param id the value for player_safe_info.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_safe_info.player_id
     *
     * @return the value of player_safe_info.player_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Long getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_safe_info.player_id
     *
     * @param playerId the value for player_safe_info.player_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setPlayerId(Long playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_safe_info.validate_phone
     *
     * @return the value of player_safe_info.validate_phone
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Boolean getValidatePhone() {
        return validatePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_safe_info.validate_phone
     *
     * @param validatePhone the value for player_safe_info.validate_phone
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setValidatePhone(Boolean validatePhone) {
        this.validatePhone = validatePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_safe_info.validate_email
     *
     * @return the value of player_safe_info.validate_email
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Boolean getValidateEmail() {
        return validateEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_safe_info.validate_email
     *
     * @param validateEmail the value for player_safe_info.validate_email
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setValidateEmail(Boolean validateEmail) {
        this.validateEmail = validateEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_safe_info.first_pwd_protect_q
     *
     * @return the value of player_safe_info.first_pwd_protect_q
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getFirstPwdProtectQ() {
        return firstPwdProtectQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_safe_info.first_pwd_protect_q
     *
     * @param firstPwdProtectQ the value for player_safe_info.first_pwd_protect_q
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setFirstPwdProtectQ(String firstPwdProtectQ) {
        this.firstPwdProtectQ = firstPwdProtectQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_safe_info.first_pwd_protect_a
     *
     * @return the value of player_safe_info.first_pwd_protect_a
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getFirstPwdProtectA() {
        return firstPwdProtectA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_safe_info.first_pwd_protect_a
     *
     * @param firstPwdProtectA the value for player_safe_info.first_pwd_protect_a
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setFirstPwdProtectA(String firstPwdProtectA) {
        this.firstPwdProtectA = firstPwdProtectA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_safe_info.second_pwd_protect_q
     *
     * @return the value of player_safe_info.second_pwd_protect_q
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getSecondPwdProtectQ() {
        return secondPwdProtectQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_safe_info.second_pwd_protect_q
     *
     * @param secondPwdProtectQ the value for player_safe_info.second_pwd_protect_q
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setSecondPwdProtectQ(String secondPwdProtectQ) {
        this.secondPwdProtectQ = secondPwdProtectQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_safe_info.second_pwd_protect_a
     *
     * @return the value of player_safe_info.second_pwd_protect_a
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getSecondPwdProtectA() {
        return secondPwdProtectA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_safe_info.second_pwd_protect_a
     *
     * @param secondPwdProtectA the value for player_safe_info.second_pwd_protect_a
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setSecondPwdProtectA(String secondPwdProtectA) {
        this.secondPwdProtectA = secondPwdProtectA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_safe_info.login_phone_verify
     *
     * @return the value of player_safe_info.login_phone_verify
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Boolean getLoginPhoneVerify() {
        return loginPhoneVerify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_safe_info.login_phone_verify
     *
     * @param loginPhoneVerify the value for player_safe_info.login_phone_verify
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setLoginPhoneVerify(Boolean loginPhoneVerify) {
        this.loginPhoneVerify = loginPhoneVerify;
    }
}