package com.idealighter.game.core.dao.generate.domain;

import java.io.Serializable;
import java.util.Date;

public class PlayerMainDomain implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.super_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Long superId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.phone
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.union_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String unionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.user_name
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.email
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.player_name
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String playerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.password
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.re_login_code
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String reLoginCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.recommend_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Long recommendId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.register_type
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Byte registerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.tourist
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Boolean tourist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.type
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.online
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Boolean online;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.icon
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Integer icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.exp
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Long exp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.level
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.ingot
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Long ingot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.gold
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Long gold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.safe_gold
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Long safeGold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.win_gold
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Long winGold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.cedit
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Long cedit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.lottery
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Long lottery;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.transfer_reward
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Long transferReward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.bank_pwd
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String bankPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.vip_level
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Integer vipLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.vip_end_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Date vipEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.locked
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Boolean locked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_main.channel_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table player_main
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.id
     *
     * @return the value of player_main.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.id
     *
     * @param id the value for player_main.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.super_id
     *
     * @return the value of player_main.super_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Long getSuperId() {
        return superId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.super_id
     *
     * @param superId the value for player_main.super_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setSuperId(Long superId) {
        this.superId = superId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.phone
     *
     * @return the value of player_main.phone
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.phone
     *
     * @param phone the value for player_main.phone
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.union_id
     *
     * @return the value of player_main.union_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.union_id
     *
     * @param unionId the value for player_main.union_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.user_name
     *
     * @return the value of player_main.user_name
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.user_name
     *
     * @param userName the value for player_main.user_name
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.email
     *
     * @return the value of player_main.email
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.email
     *
     * @param email the value for player_main.email
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.player_name
     *
     * @return the value of player_main.player_name
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getPlayerName() {
        return playerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.player_name
     *
     * @param playerName the value for player_main.player_name
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setPlayerName(String playerName) {
        this.playerName = playerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.password
     *
     * @return the value of player_main.password
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.password
     *
     * @param password the value for player_main.password
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.re_login_code
     *
     * @return the value of player_main.re_login_code
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getReLoginCode() {
        return reLoginCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.re_login_code
     *
     * @param reLoginCode the value for player_main.re_login_code
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setReLoginCode(String reLoginCode) {
        this.reLoginCode = reLoginCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.recommend_id
     *
     * @return the value of player_main.recommend_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Long getRecommendId() {
        return recommendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.recommend_id
     *
     * @param recommendId the value for player_main.recommend_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setRecommendId(Long recommendId) {
        this.recommendId = recommendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.register_type
     *
     * @return the value of player_main.register_type
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Byte getRegisterType() {
        return registerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.register_type
     *
     * @param registerType the value for player_main.register_type
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setRegisterType(Byte registerType) {
        this.registerType = registerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.tourist
     *
     * @return the value of player_main.tourist
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Boolean getTourist() {
        return tourist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.tourist
     *
     * @param tourist the value for player_main.tourist
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setTourist(Boolean tourist) {
        this.tourist = tourist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.type
     *
     * @return the value of player_main.type
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.type
     *
     * @param type the value for player_main.type
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.online
     *
     * @return the value of player_main.online
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Boolean getOnline() {
        return online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.online
     *
     * @param online the value for player_main.online
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setOnline(Boolean online) {
        this.online = online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.icon
     *
     * @return the value of player_main.icon
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Integer getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.icon
     *
     * @param icon the value for player_main.icon
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setIcon(Integer icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.exp
     *
     * @return the value of player_main.exp
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Long getExp() {
        return exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.exp
     *
     * @param exp the value for player_main.exp
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setExp(Long exp) {
        this.exp = exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.level
     *
     * @return the value of player_main.level
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.level
     *
     * @param level the value for player_main.level
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.ingot
     *
     * @return the value of player_main.ingot
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Long getIngot() {
        return ingot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.ingot
     *
     * @param ingot the value for player_main.ingot
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setIngot(Long ingot) {
        this.ingot = ingot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.gold
     *
     * @return the value of player_main.gold
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Long getGold() {
        return gold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.gold
     *
     * @param gold the value for player_main.gold
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setGold(Long gold) {
        this.gold = gold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.safe_gold
     *
     * @return the value of player_main.safe_gold
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Long getSafeGold() {
        return safeGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.safe_gold
     *
     * @param safeGold the value for player_main.safe_gold
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setSafeGold(Long safeGold) {
        this.safeGold = safeGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.win_gold
     *
     * @return the value of player_main.win_gold
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Long getWinGold() {
        return winGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.win_gold
     *
     * @param winGold the value for player_main.win_gold
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setWinGold(Long winGold) {
        this.winGold = winGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.cedit
     *
     * @return the value of player_main.cedit
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Long getCedit() {
        return cedit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.cedit
     *
     * @param cedit the value for player_main.cedit
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setCedit(Long cedit) {
        this.cedit = cedit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.lottery
     *
     * @return the value of player_main.lottery
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Long getLottery() {
        return lottery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.lottery
     *
     * @param lottery the value for player_main.lottery
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setLottery(Long lottery) {
        this.lottery = lottery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.transfer_reward
     *
     * @return the value of player_main.transfer_reward
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Long getTransferReward() {
        return transferReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.transfer_reward
     *
     * @param transferReward the value for player_main.transfer_reward
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setTransferReward(Long transferReward) {
        this.transferReward = transferReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.bank_pwd
     *
     * @return the value of player_main.bank_pwd
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getBankPwd() {
        return bankPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.bank_pwd
     *
     * @param bankPwd the value for player_main.bank_pwd
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setBankPwd(String bankPwd) {
        this.bankPwd = bankPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.vip_level
     *
     * @return the value of player_main.vip_level
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Integer getVipLevel() {
        return vipLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.vip_level
     *
     * @param vipLevel the value for player_main.vip_level
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setVipLevel(Integer vipLevel) {
        this.vipLevel = vipLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.vip_end_time
     *
     * @return the value of player_main.vip_end_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Date getVipEndTime() {
        return vipEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.vip_end_time
     *
     * @param vipEndTime the value for player_main.vip_end_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setVipEndTime(Date vipEndTime) {
        this.vipEndTime = vipEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.locked
     *
     * @return the value of player_main.locked
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Boolean getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.locked
     *
     * @param locked the value for player_main.locked
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setLocked(Boolean locked) {
        this.locked = locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_main.channel_id
     *
     * @return the value of player_main.channel_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_main.channel_id
     *
     * @param channelId the value for player_main.channel_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }
}