package com.idealighter.game.core.dao.generate.domain;

import java.io.Serializable;

public class PlayerGameInfoDomainWithBLOBs extends PlayerGameInfoDomain implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_game_info.prize_pools
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String prizePools;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_game_info.items
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String items;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table player_game_info
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_game_info.prize_pools
     *
     * @return the value of player_game_info.prize_pools
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getPrizePools() {
        return prizePools;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_game_info.prize_pools
     *
     * @param prizePools the value for player_game_info.prize_pools
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setPrizePools(String prizePools) {
        this.prizePools = prizePools;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_game_info.items
     *
     * @return the value of player_game_info.items
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getItems() {
        return items;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_game_info.items
     *
     * @param items the value for player_game_info.items
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setItems(String items) {
        this.items = items;
    }
}