package com.idealighter.game.core.dao.generate.domain;

import java.io.Serializable;
import java.util.Date;

public class RechargeRecordDomain implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_record.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_record.trade_no
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String tradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_record.outside_no
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String outsideNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_record.pay_type
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Byte payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_record.player_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Long playerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_record.recharge_item_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Integer rechargeItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_record.gold
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Long gold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_record.send_gold
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Long sendGold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_record.price
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_record.create_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_record.pay_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_record.state
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recharge_record
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_record.id
     *
     * @return the value of recharge_record.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_record.id
     *
     * @param id the value for recharge_record.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_record.trade_no
     *
     * @return the value of recharge_record.trade_no
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_record.trade_no
     *
     * @param tradeNo the value for recharge_record.trade_no
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_record.outside_no
     *
     * @return the value of recharge_record.outside_no
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getOutsideNo() {
        return outsideNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_record.outside_no
     *
     * @param outsideNo the value for recharge_record.outside_no
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setOutsideNo(String outsideNo) {
        this.outsideNo = outsideNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_record.pay_type
     *
     * @return the value of recharge_record.pay_type
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Byte getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_record.pay_type
     *
     * @param payType the value for recharge_record.pay_type
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setPayType(Byte payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_record.player_id
     *
     * @return the value of recharge_record.player_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Long getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_record.player_id
     *
     * @param playerId the value for recharge_record.player_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setPlayerId(Long playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_record.recharge_item_id
     *
     * @return the value of recharge_record.recharge_item_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Integer getRechargeItemId() {
        return rechargeItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_record.recharge_item_id
     *
     * @param rechargeItemId the value for recharge_record.recharge_item_id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setRechargeItemId(Integer rechargeItemId) {
        this.rechargeItemId = rechargeItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_record.gold
     *
     * @return the value of recharge_record.gold
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Long getGold() {
        return gold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_record.gold
     *
     * @param gold the value for recharge_record.gold
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setGold(Long gold) {
        this.gold = gold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_record.send_gold
     *
     * @return the value of recharge_record.send_gold
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Long getSendGold() {
        return sendGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_record.send_gold
     *
     * @param sendGold the value for recharge_record.send_gold
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setSendGold(Long sendGold) {
        this.sendGold = sendGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_record.price
     *
     * @return the value of recharge_record.price
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_record.price
     *
     * @param price the value for recharge_record.price
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_record.create_time
     *
     * @return the value of recharge_record.create_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_record.create_time
     *
     * @param createTime the value for recharge_record.create_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_record.pay_time
     *
     * @return the value of recharge_record.pay_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_record.pay_time
     *
     * @param payTime the value for recharge_record.pay_time
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_record.state
     *
     * @return the value of recharge_record.state
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_record.state
     *
     * @param state the value for recharge_record.state
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setState(Byte state) {
        this.state = state;
    }
}