package com.idealighter.game.core.dao.generate.domain;

import java.io.Serializable;

public class WhiteListDomain implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column white_list.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column white_list.account
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table white_list
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column white_list.id
     *
     * @return the value of white_list.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column white_list.id
     *
     * @param id the value for white_list.id
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column white_list.account
     *
     * @return the value of white_list.account
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column white_list.account
     *
     * @param account the value for white_list.account
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public void setAccount(String account) {
        this.account = account;
    }
}