package com.idealighter.game.core.dao.generate.mapper;

import com.idealighter.game.core.dao.generate.domain.MailDomain;
import com.idealighter.game.core.dao.generate.domain.MailDomainExample.Criteria;
import com.idealighter.game.core.dao.generate.domain.MailDomainExample.Criterion;
import com.idealighter.game.core.dao.generate.domain.MailDomainExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class MailDomainSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String countByExample(MailDomainExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("mail");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String deleteByExample(MailDomainExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("mail");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String insertSelective(MailDomain record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("mail");
        
        if (record.getPlayerId() != null) {
            sql.VALUES("player_id", "#{playerId,jdbcType=BIGINT}");
        }
        
        if (record.getPlayerSuperId() != null) {
            sql.VALUES("player_super_id", "#{playerSuperId,jdbcType=BIGINT}");
        }
        
        if (record.getPlayerName() != null) {
            sql.VALUES("player_name", "#{playerName,jdbcType=VARCHAR}");
        }
        
        if (record.getFromPlayerId() != null) {
            sql.VALUES("from_player_id", "#{fromPlayerId,jdbcType=BIGINT}");
        }
        
        if (record.getFromPlayerSuperId() != null) {
            sql.VALUES("from_player_super_id", "#{fromPlayerSuperId,jdbcType=BIGINT}");
        }
        
        if (record.getFromPlayerName() != null) {
            sql.VALUES("from_player_name", "#{fromPlayerName,jdbcType=VARCHAR}");
        }
        
        if (record.getGold() != null) {
            sql.VALUES("gold", "#{gold,jdbcType=BIGINT}");
        }
        
        if (record.getTitle() != null) {
            sql.VALUES("title", "#{title,jdbcType=VARCHAR}");
        }
        
        if (record.getIsRead() != null) {
            sql.VALUES("is_read", "#{isRead,jdbcType=BIT}");
        }
        
        if (record.getIsRecGold() != null) {
            sql.VALUES("is_rec_gold", "#{isRecGold,jdbcType=BIT}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getContent() != null) {
            sql.VALUES("content", "#{content,jdbcType=LONGVARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String selectByExampleWithBLOBs(MailDomainExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("player_id");
        sql.SELECT("player_super_id");
        sql.SELECT("player_name");
        sql.SELECT("from_player_id");
        sql.SELECT("from_player_super_id");
        sql.SELECT("from_player_name");
        sql.SELECT("gold");
        sql.SELECT("title");
        sql.SELECT("is_read");
        sql.SELECT("is_rec_gold");
        sql.SELECT("create_time");
        sql.SELECT("content");
        sql.FROM("mail");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        String tmp = "";
        if (example != null && example.getLimit() != null) {
            tmp = " limit " + example.getLimit().toString();
            if (example.getOffset() != null) {
                tmp = tmp + " offset " + example.getOffset().toString();
            }
        }
        return sql + tmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String selectByExample(MailDomainExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("player_id");
        sql.SELECT("player_super_id");
        sql.SELECT("player_name");
        sql.SELECT("from_player_id");
        sql.SELECT("from_player_super_id");
        sql.SELECT("from_player_name");
        sql.SELECT("gold");
        sql.SELECT("title");
        sql.SELECT("is_read");
        sql.SELECT("is_rec_gold");
        sql.SELECT("create_time");
        sql.FROM("mail");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        String tmp = "";
        if (example != null && example.getLimit() != null) {
            tmp = " limit " + example.getLimit().toString();
            if (example.getOffset() != null) {
                tmp = tmp + " offset " + example.getOffset().toString();
            }
        }
        return sql + tmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        MailDomain record = (MailDomain) parameter.get("record");
        MailDomainExample example = (MailDomainExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("mail");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getPlayerId() != null) {
            sql.SET("player_id = #{record.playerId,jdbcType=BIGINT}");
        }
        
        if (record.getPlayerSuperId() != null) {
            sql.SET("player_super_id = #{record.playerSuperId,jdbcType=BIGINT}");
        }
        
        if (record.getPlayerName() != null) {
            sql.SET("player_name = #{record.playerName,jdbcType=VARCHAR}");
        }
        
        if (record.getFromPlayerId() != null) {
            sql.SET("from_player_id = #{record.fromPlayerId,jdbcType=BIGINT}");
        }
        
        if (record.getFromPlayerSuperId() != null) {
            sql.SET("from_player_super_id = #{record.fromPlayerSuperId,jdbcType=BIGINT}");
        }
        
        if (record.getFromPlayerName() != null) {
            sql.SET("from_player_name = #{record.fromPlayerName,jdbcType=VARCHAR}");
        }
        
        if (record.getGold() != null) {
            sql.SET("gold = #{record.gold,jdbcType=BIGINT}");
        }
        
        if (record.getTitle() != null) {
            sql.SET("title = #{record.title,jdbcType=VARCHAR}");
        }
        
        if (record.getIsRead() != null) {
            sql.SET("is_read = #{record.isRead,jdbcType=BIT}");
        }
        
        if (record.getIsRecGold() != null) {
            sql.SET("is_rec_gold = #{record.isRecGold,jdbcType=BIT}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getContent() != null) {
            sql.SET("content = #{record.content,jdbcType=LONGVARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String updateByExampleWithBLOBs(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("mail");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("player_id = #{record.playerId,jdbcType=BIGINT}");
        sql.SET("player_super_id = #{record.playerSuperId,jdbcType=BIGINT}");
        sql.SET("player_name = #{record.playerName,jdbcType=VARCHAR}");
        sql.SET("from_player_id = #{record.fromPlayerId,jdbcType=BIGINT}");
        sql.SET("from_player_super_id = #{record.fromPlayerSuperId,jdbcType=BIGINT}");
        sql.SET("from_player_name = #{record.fromPlayerName,jdbcType=VARCHAR}");
        sql.SET("gold = #{record.gold,jdbcType=BIGINT}");
        sql.SET("title = #{record.title,jdbcType=VARCHAR}");
        sql.SET("is_read = #{record.isRead,jdbcType=BIT}");
        sql.SET("is_rec_gold = #{record.isRecGold,jdbcType=BIT}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("content = #{record.content,jdbcType=LONGVARCHAR}");
        
        MailDomainExample example = (MailDomainExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("mail");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("player_id = #{record.playerId,jdbcType=BIGINT}");
        sql.SET("player_super_id = #{record.playerSuperId,jdbcType=BIGINT}");
        sql.SET("player_name = #{record.playerName,jdbcType=VARCHAR}");
        sql.SET("from_player_id = #{record.fromPlayerId,jdbcType=BIGINT}");
        sql.SET("from_player_super_id = #{record.fromPlayerSuperId,jdbcType=BIGINT}");
        sql.SET("from_player_name = #{record.fromPlayerName,jdbcType=VARCHAR}");
        sql.SET("gold = #{record.gold,jdbcType=BIGINT}");
        sql.SET("title = #{record.title,jdbcType=VARCHAR}");
        sql.SET("is_read = #{record.isRead,jdbcType=BIT}");
        sql.SET("is_rec_gold = #{record.isRecGold,jdbcType=BIT}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        
        MailDomainExample example = (MailDomainExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String updateByPrimaryKeySelective(MailDomain record) {
        SQL sql = new SQL();
        sql.UPDATE("mail");
        
        if (record.getPlayerId() != null) {
            sql.SET("player_id = #{playerId,jdbcType=BIGINT}");
        }
        
        if (record.getPlayerSuperId() != null) {
            sql.SET("player_super_id = #{playerSuperId,jdbcType=BIGINT}");
        }
        
        if (record.getPlayerName() != null) {
            sql.SET("player_name = #{playerName,jdbcType=VARCHAR}");
        }
        
        if (record.getFromPlayerId() != null) {
            sql.SET("from_player_id = #{fromPlayerId,jdbcType=BIGINT}");
        }
        
        if (record.getFromPlayerSuperId() != null) {
            sql.SET("from_player_super_id = #{fromPlayerSuperId,jdbcType=BIGINT}");
        }
        
        if (record.getFromPlayerName() != null) {
            sql.SET("from_player_name = #{fromPlayerName,jdbcType=VARCHAR}");
        }
        
        if (record.getGold() != null) {
            sql.SET("gold = #{gold,jdbcType=BIGINT}");
        }
        
        if (record.getTitle() != null) {
            sql.SET("title = #{title,jdbcType=VARCHAR}");
        }
        
        if (record.getIsRead() != null) {
            sql.SET("is_read = #{isRead,jdbcType=BIT}");
        }
        
        if (record.getIsRecGold() != null) {
            sql.SET("is_rec_gold = #{isRecGold,jdbcType=BIT}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getContent() != null) {
            sql.SET("content = #{content,jdbcType=LONGVARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    protected void applyWhere(SQL sql, MailDomainExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}