package com.idealighter.game.core.dao.generate.mapper;

import com.idealighter.game.core.dao.generate.domain.PlayerVipDomain;
import com.idealighter.game.core.dao.generate.domain.PlayerVipDomainExample.Criteria;
import com.idealighter.game.core.dao.generate.domain.PlayerVipDomainExample.Criterion;
import com.idealighter.game.core.dao.generate.domain.PlayerVipDomainExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class PlayerVipDomainSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_vip
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String countByExample(PlayerVipDomainExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("player_vip");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_vip
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String deleteByExample(PlayerVipDomainExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("player_vip");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_vip
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String insertSelective(PlayerVipDomain record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("player_vip");
        
        if (record.getPlayerId() != null) {
            sql.VALUES("player_id", "#{playerId,jdbcType=BIGINT}");
        }
        
        if (record.getPlayItemEffect() != null) {
            sql.VALUES("play_item_effect", "#{playItemEffect,jdbcType=BIT}");
        }
        
        if (record.getTableLimitGold() != null) {
            sql.VALUES("table_limit_gold", "#{tableLimitGold,jdbcType=BIGINT}");
        }
        
        if (record.getTableLimitGoldAbled() != null) {
            sql.VALUES("table_limit_gold_abled", "#{tableLimitGoldAbled,jdbcType=BIT}");
        }
        
        if (record.getTableLimitIp() != null) {
            sql.VALUES("table_limit_ip", "#{tableLimitIp,jdbcType=BIT}");
        }
        
        if (record.getTablePwd() != null) {
            sql.VALUES("table_pwd", "#{tablePwd,jdbcType=VARCHAR}");
        }
        
        if (record.getTablePwdAbled() != null) {
            sql.VALUES("table_pwd_abled", "#{tablePwdAbled,jdbcType=BIT}");
        }
        
        if (record.getRoomSettingAbled() != null) {
            sql.VALUES("room_setting_abled", "#{roomSettingAbled,jdbcType=BIT}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_vip
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String selectByExample(PlayerVipDomainExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("player_id");
        sql.SELECT("play_item_effect");
        sql.SELECT("table_limit_gold");
        sql.SELECT("table_limit_gold_abled");
        sql.SELECT("table_limit_ip");
        sql.SELECT("table_pwd");
        sql.SELECT("table_pwd_abled");
        sql.SELECT("room_setting_abled");
        sql.FROM("player_vip");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        String tmp = "";
        if (example != null && example.getLimit() != null) {
            tmp = " limit " + example.getLimit().toString();
            if (example.getOffset() != null) {
                tmp = tmp + " offset " + example.getOffset().toString();
            }
        }
        return sql + tmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_vip
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        PlayerVipDomain record = (PlayerVipDomain) parameter.get("record");
        PlayerVipDomainExample example = (PlayerVipDomainExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("player_vip");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getPlayerId() != null) {
            sql.SET("player_id = #{record.playerId,jdbcType=BIGINT}");
        }
        
        if (record.getPlayItemEffect() != null) {
            sql.SET("play_item_effect = #{record.playItemEffect,jdbcType=BIT}");
        }
        
        if (record.getTableLimitGold() != null) {
            sql.SET("table_limit_gold = #{record.tableLimitGold,jdbcType=BIGINT}");
        }
        
        if (record.getTableLimitGoldAbled() != null) {
            sql.SET("table_limit_gold_abled = #{record.tableLimitGoldAbled,jdbcType=BIT}");
        }
        
        if (record.getTableLimitIp() != null) {
            sql.SET("table_limit_ip = #{record.tableLimitIp,jdbcType=BIT}");
        }
        
        if (record.getTablePwd() != null) {
            sql.SET("table_pwd = #{record.tablePwd,jdbcType=VARCHAR}");
        }
        
        if (record.getTablePwdAbled() != null) {
            sql.SET("table_pwd_abled = #{record.tablePwdAbled,jdbcType=BIT}");
        }
        
        if (record.getRoomSettingAbled() != null) {
            sql.SET("room_setting_abled = #{record.roomSettingAbled,jdbcType=BIT}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_vip
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("player_vip");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("player_id = #{record.playerId,jdbcType=BIGINT}");
        sql.SET("play_item_effect = #{record.playItemEffect,jdbcType=BIT}");
        sql.SET("table_limit_gold = #{record.tableLimitGold,jdbcType=BIGINT}");
        sql.SET("table_limit_gold_abled = #{record.tableLimitGoldAbled,jdbcType=BIT}");
        sql.SET("table_limit_ip = #{record.tableLimitIp,jdbcType=BIT}");
        sql.SET("table_pwd = #{record.tablePwd,jdbcType=VARCHAR}");
        sql.SET("table_pwd_abled = #{record.tablePwdAbled,jdbcType=BIT}");
        sql.SET("room_setting_abled = #{record.roomSettingAbled,jdbcType=BIT}");
        
        PlayerVipDomainExample example = (PlayerVipDomainExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_vip
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String updateByPrimaryKeySelective(PlayerVipDomain record) {
        SQL sql = new SQL();
        sql.UPDATE("player_vip");
        
        if (record.getPlayerId() != null) {
            sql.SET("player_id = #{playerId,jdbcType=BIGINT}");
        }
        
        if (record.getPlayItemEffect() != null) {
            sql.SET("play_item_effect = #{playItemEffect,jdbcType=BIT}");
        }
        
        if (record.getTableLimitGold() != null) {
            sql.SET("table_limit_gold = #{tableLimitGold,jdbcType=BIGINT}");
        }
        
        if (record.getTableLimitGoldAbled() != null) {
            sql.SET("table_limit_gold_abled = #{tableLimitGoldAbled,jdbcType=BIT}");
        }
        
        if (record.getTableLimitIp() != null) {
            sql.SET("table_limit_ip = #{tableLimitIp,jdbcType=BIT}");
        }
        
        if (record.getTablePwd() != null) {
            sql.SET("table_pwd = #{tablePwd,jdbcType=VARCHAR}");
        }
        
        if (record.getTablePwdAbled() != null) {
            sql.SET("table_pwd_abled = #{tablePwdAbled,jdbcType=BIT}");
        }
        
        if (record.getRoomSettingAbled() != null) {
            sql.SET("room_setting_abled = #{roomSettingAbled,jdbcType=BIT}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_vip
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    protected void applyWhere(SQL sql, PlayerVipDomainExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}