package com.idealighter.game.core.dao.generate.mapper;

import com.idealighter.game.core.dao.generate.domain.RoomPrizePoolGoupDomain;
import com.idealighter.game.core.dao.generate.domain.RoomPrizePoolGoupDomainExample;
import com.idealighter.game.core.dao.generate.domain.RoomPrizePoolGoupDomainKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface RoomPrizePoolGoupDomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_prize_pool_group
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    @SelectProvider(type=RoomPrizePoolGoupDomainSqlProvider.class, method="countByExample")
    long countByExample(RoomPrizePoolGoupDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_prize_pool_group
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    @DeleteProvider(type=RoomPrizePoolGoupDomainSqlProvider.class, method="deleteByExample")
    int deleteByExample(RoomPrizePoolGoupDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_prize_pool_group
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    @Delete({
        "delete from room_prize_pool_group",
        "where game = #{game,jdbcType=INTEGER}",
          "and room_id = #{roomId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(RoomPrizePoolGoupDomainKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_prize_pool_group
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    @Insert({
        "insert into room_prize_pool_group (game, room_id, ",
        "default_prize_pool, create_time, ",
        "update_time, prize_pools)",
        "values (#{game,jdbcType=INTEGER}, #{roomId,jdbcType=INTEGER}, ",
        "#{defaultPrizePool,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{prizePools,jdbcType=LONGVARCHAR})"
    })
    int insert(RoomPrizePoolGoupDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_prize_pool_group
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    @InsertProvider(type=RoomPrizePoolGoupDomainSqlProvider.class, method="insertSelective")
    int insertSelective(RoomPrizePoolGoupDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_prize_pool_group
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    @SelectProvider(type=RoomPrizePoolGoupDomainSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="game", property="game", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="room_id", property="roomId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="default_prize_pool", property="defaultPrizePool", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="prize_pools", property="prizePools", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<RoomPrizePoolGoupDomain> selectByExampleWithBLOBs(RoomPrizePoolGoupDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_prize_pool_group
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    @SelectProvider(type=RoomPrizePoolGoupDomainSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="game", property="game", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="room_id", property="roomId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="default_prize_pool", property="defaultPrizePool", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<RoomPrizePoolGoupDomain> selectByExample(RoomPrizePoolGoupDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_prize_pool_group
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    @Select({
        "select",
        "game, room_id, default_prize_pool, create_time, update_time, prize_pools",
        "from room_prize_pool_group",
        "where game = #{game,jdbcType=INTEGER}",
          "and room_id = #{roomId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="game", property="game", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="room_id", property="roomId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="default_prize_pool", property="defaultPrizePool", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="prize_pools", property="prizePools", jdbcType=JdbcType.LONGVARCHAR)
    })
    RoomPrizePoolGoupDomain selectByPrimaryKey(RoomPrizePoolGoupDomainKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_prize_pool_group
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    @UpdateProvider(type=RoomPrizePoolGoupDomainSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") RoomPrizePoolGoupDomain record, @Param("example") RoomPrizePoolGoupDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_prize_pool_group
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    @UpdateProvider(type=RoomPrizePoolGoupDomainSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") RoomPrizePoolGoupDomain record, @Param("example") RoomPrizePoolGoupDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_prize_pool_group
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    @UpdateProvider(type=RoomPrizePoolGoupDomainSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") RoomPrizePoolGoupDomain record, @Param("example") RoomPrizePoolGoupDomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_prize_pool_group
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    @UpdateProvider(type=RoomPrizePoolGoupDomainSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(RoomPrizePoolGoupDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_prize_pool_group
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    @Update({
        "update room_prize_pool_group",
        "set default_prize_pool = #{defaultPrizePool,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "prize_pools = #{prizePools,jdbcType=LONGVARCHAR}",
        "where game = #{game,jdbcType=INTEGER}",
          "and room_id = #{roomId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(RoomPrizePoolGoupDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_prize_pool_group
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    @Update({
        "update room_prize_pool_group",
        "set default_prize_pool = #{defaultPrizePool,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where game = #{game,jdbcType=INTEGER}",
          "and room_id = #{roomId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(RoomPrizePoolGoupDomain record);
}