package com.idealighter.game.core.dao.generate.mapper;

import com.idealighter.game.core.dao.generate.domain.TransferGoldRecordDomain;
import com.idealighter.game.core.dao.generate.domain.TransferGoldRecordDomainExample.Criteria;
import com.idealighter.game.core.dao.generate.domain.TransferGoldRecordDomainExample.Criterion;
import com.idealighter.game.core.dao.generate.domain.TransferGoldRecordDomainExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class TransferGoldRecordDomainSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_gold_record
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String countByExample(TransferGoldRecordDomainExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("transfer_gold_record");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_gold_record
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String deleteByExample(TransferGoldRecordDomainExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("transfer_gold_record");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_gold_record
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String insertSelective(TransferGoldRecordDomain record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("transfer_gold_record");
        
        if (record.getType() != null) {
            sql.VALUES("type", "#{type,jdbcType=TINYINT}");
        }
        
        if (record.getOppositeType() != null) {
            sql.VALUES("opposite_type", "#{oppositeType,jdbcType=TINYINT}");
        }
        
        if (record.getPlayerId() != null) {
            sql.VALUES("player_id", "#{playerId,jdbcType=BIGINT}");
        }
        
        if (record.getPlayerSuperId() != null) {
            sql.VALUES("player_super_id", "#{playerSuperId,jdbcType=BIGINT}");
        }
        
        if (record.getPlayerName() != null) {
            sql.VALUES("player_name", "#{playerName,jdbcType=VARCHAR}");
        }
        
        if (record.getOppositePlayerId() != null) {
            sql.VALUES("opposite_player_id", "#{oppositePlayerId,jdbcType=BIGINT}");
        }
        
        if (record.getOppositeSuperId() != null) {
            sql.VALUES("opposite_super_id", "#{oppositeSuperId,jdbcType=BIGINT}");
        }
        
        if (record.getOppositePlayerName() != null) {
            sql.VALUES("opposite_player_name", "#{oppositePlayerName,jdbcType=VARCHAR}");
        }
        
        if (record.getBeforeSafeGold() != null) {
            sql.VALUES("before_safe_gold", "#{beforeSafeGold,jdbcType=BIGINT}");
        }
        
        if (record.getAfterSafeGold() != null) {
            sql.VALUES("after_safe_gold", "#{afterSafeGold,jdbcType=BIGINT}");
        }
        
        if (record.getFee() != null) {
            sql.VALUES("fee", "#{fee,jdbcType=BIGINT}");
        }
        
        if (record.getFeeRate() != null) {
            sql.VALUES("fee_rate", "#{feeRate,jdbcType=INTEGER}");
        }
        
        if (record.getChangeSafeGold() != null) {
            sql.VALUES("change_safe_gold", "#{changeSafeGold,jdbcType=BIGINT}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getPlayerType() != null) {
            sql.VALUES("player_type", "#{playerType,jdbcType=TINYINT}");
        }
        
        if (record.getChannelId() != null) {
            sql.VALUES("channel_id", "#{channelId,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_gold_record
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String selectByExample(TransferGoldRecordDomainExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("type");
        sql.SELECT("opposite_type");
        sql.SELECT("player_id");
        sql.SELECT("player_super_id");
        sql.SELECT("player_name");
        sql.SELECT("opposite_player_id");
        sql.SELECT("opposite_super_id");
        sql.SELECT("opposite_player_name");
        sql.SELECT("before_safe_gold");
        sql.SELECT("after_safe_gold");
        sql.SELECT("fee");
        sql.SELECT("fee_rate");
        sql.SELECT("change_safe_gold");
        sql.SELECT("create_time");
        sql.SELECT("player_type");
        sql.SELECT("channel_id");
        sql.FROM("transfer_gold_record");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        String tmp = "";
        if (example != null && example.getLimit() != null) {
            tmp = " limit " + example.getLimit().toString();
            if (example.getOffset() != null) {
                tmp = tmp + " offset " + example.getOffset().toString();
            }
        }
        return sql + tmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_gold_record
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TransferGoldRecordDomain record = (TransferGoldRecordDomain) parameter.get("record");
        TransferGoldRecordDomainExample example = (TransferGoldRecordDomainExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("transfer_gold_record");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getType() != null) {
            sql.SET("type = #{record.type,jdbcType=TINYINT}");
        }
        
        if (record.getOppositeType() != null) {
            sql.SET("opposite_type = #{record.oppositeType,jdbcType=TINYINT}");
        }
        
        if (record.getPlayerId() != null) {
            sql.SET("player_id = #{record.playerId,jdbcType=BIGINT}");
        }
        
        if (record.getPlayerSuperId() != null) {
            sql.SET("player_super_id = #{record.playerSuperId,jdbcType=BIGINT}");
        }
        
        if (record.getPlayerName() != null) {
            sql.SET("player_name = #{record.playerName,jdbcType=VARCHAR}");
        }
        
        if (record.getOppositePlayerId() != null) {
            sql.SET("opposite_player_id = #{record.oppositePlayerId,jdbcType=BIGINT}");
        }
        
        if (record.getOppositeSuperId() != null) {
            sql.SET("opposite_super_id = #{record.oppositeSuperId,jdbcType=BIGINT}");
        }
        
        if (record.getOppositePlayerName() != null) {
            sql.SET("opposite_player_name = #{record.oppositePlayerName,jdbcType=VARCHAR}");
        }
        
        if (record.getBeforeSafeGold() != null) {
            sql.SET("before_safe_gold = #{record.beforeSafeGold,jdbcType=BIGINT}");
        }
        
        if (record.getAfterSafeGold() != null) {
            sql.SET("after_safe_gold = #{record.afterSafeGold,jdbcType=BIGINT}");
        }
        
        if (record.getFee() != null) {
            sql.SET("fee = #{record.fee,jdbcType=BIGINT}");
        }
        
        if (record.getFeeRate() != null) {
            sql.SET("fee_rate = #{record.feeRate,jdbcType=INTEGER}");
        }
        
        if (record.getChangeSafeGold() != null) {
            sql.SET("change_safe_gold = #{record.changeSafeGold,jdbcType=BIGINT}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getPlayerType() != null) {
            sql.SET("player_type = #{record.playerType,jdbcType=TINYINT}");
        }
        
        if (record.getChannelId() != null) {
            sql.SET("channel_id = #{record.channelId,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_gold_record
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("transfer_gold_record");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("type = #{record.type,jdbcType=TINYINT}");
        sql.SET("opposite_type = #{record.oppositeType,jdbcType=TINYINT}");
        sql.SET("player_id = #{record.playerId,jdbcType=BIGINT}");
        sql.SET("player_super_id = #{record.playerSuperId,jdbcType=BIGINT}");
        sql.SET("player_name = #{record.playerName,jdbcType=VARCHAR}");
        sql.SET("opposite_player_id = #{record.oppositePlayerId,jdbcType=BIGINT}");
        sql.SET("opposite_super_id = #{record.oppositeSuperId,jdbcType=BIGINT}");
        sql.SET("opposite_player_name = #{record.oppositePlayerName,jdbcType=VARCHAR}");
        sql.SET("before_safe_gold = #{record.beforeSafeGold,jdbcType=BIGINT}");
        sql.SET("after_safe_gold = #{record.afterSafeGold,jdbcType=BIGINT}");
        sql.SET("fee = #{record.fee,jdbcType=BIGINT}");
        sql.SET("fee_rate = #{record.feeRate,jdbcType=INTEGER}");
        sql.SET("change_safe_gold = #{record.changeSafeGold,jdbcType=BIGINT}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("player_type = #{record.playerType,jdbcType=TINYINT}");
        sql.SET("channel_id = #{record.channelId,jdbcType=VARCHAR}");
        
        TransferGoldRecordDomainExample example = (TransferGoldRecordDomainExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_gold_record
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    public String updateByPrimaryKeySelective(TransferGoldRecordDomain record) {
        SQL sql = new SQL();
        sql.UPDATE("transfer_gold_record");
        
        if (record.getType() != null) {
            sql.SET("type = #{type,jdbcType=TINYINT}");
        }
        
        if (record.getOppositeType() != null) {
            sql.SET("opposite_type = #{oppositeType,jdbcType=TINYINT}");
        }
        
        if (record.getPlayerId() != null) {
            sql.SET("player_id = #{playerId,jdbcType=BIGINT}");
        }
        
        if (record.getPlayerSuperId() != null) {
            sql.SET("player_super_id = #{playerSuperId,jdbcType=BIGINT}");
        }
        
        if (record.getPlayerName() != null) {
            sql.SET("player_name = #{playerName,jdbcType=VARCHAR}");
        }
        
        if (record.getOppositePlayerId() != null) {
            sql.SET("opposite_player_id = #{oppositePlayerId,jdbcType=BIGINT}");
        }
        
        if (record.getOppositeSuperId() != null) {
            sql.SET("opposite_super_id = #{oppositeSuperId,jdbcType=BIGINT}");
        }
        
        if (record.getOppositePlayerName() != null) {
            sql.SET("opposite_player_name = #{oppositePlayerName,jdbcType=VARCHAR}");
        }
        
        if (record.getBeforeSafeGold() != null) {
            sql.SET("before_safe_gold = #{beforeSafeGold,jdbcType=BIGINT}");
        }
        
        if (record.getAfterSafeGold() != null) {
            sql.SET("after_safe_gold = #{afterSafeGold,jdbcType=BIGINT}");
        }
        
        if (record.getFee() != null) {
            sql.SET("fee = #{fee,jdbcType=BIGINT}");
        }
        
        if (record.getFeeRate() != null) {
            sql.SET("fee_rate = #{feeRate,jdbcType=INTEGER}");
        }
        
        if (record.getChangeSafeGold() != null) {
            sql.SET("change_safe_gold = #{changeSafeGold,jdbcType=BIGINT}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getPlayerType() != null) {
            sql.SET("player_type = #{playerType,jdbcType=TINYINT}");
        }
        
        if (record.getChannelId() != null) {
            sql.SET("channel_id = #{channelId,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_gold_record
     *
     * @mbg.generated Tue Aug 14 14:13:21 CST 2018
     */
    protected void applyWhere(SQL sql, TransferGoldRecordDomainExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}